name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: release
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4

      - name: Test
        run: dotnet test -c ${{ env.BUILD_CONFIG }} --no-restore
